directories:
  output: dist
  buildResources: build
appId: com.electron.autoupdates
productName: autoupdates
publish:
  provider: github
linux:
  target:
    - snap
    - AppImage
    - deb
    - ram
win:
  target:
    - nsis
  icon: icon.ico
nsis:
  oneClick: true
  installerIcon: icon.ico
  uninstallerIcon: icon.ico
  uninstallDisplayName: uninstall autoupdates
  allowToChangeInstallationDirectory: false
files: []
electronVersion: 22.0.3
